const mock_users: MockUser[] = [
  {
    id: 1,
    name: "Ali Valiyev",
    message: "Salom, yaxshimisiz?",
    lastMessageTime: "09:12",
    unreadCount: 2,
    isOnline: true,
  },
  {
    id: 2,
    name: "Dilnoza Karimova",
    message: "Bugun vaqtingiz bormi?",
    lastMessageTime: "10:45",
    unreadCount: 0,
    isOnline: false,
  },
  {
    id: 3,
    name: "Bekzod Rasulov",
    message: "Loyihani tugataylik 🚀",
    lastMessageTime: "Kecha",
    unreadCount: 5,
    isOnline: true,
  },
  {
    id: 4,
    name: "Madina Tursunova",
    message: "Xayrli tong ☀️",
    lastMessageTime: "08:01",
    unreadCount: 1,
    isOnline: false,
  },
  {
    id: 5,
    name: "Jasur Abduvaliyev",
    message: "Yangilanishni ko‘rdingizmi?",
    lastMessageTime: "11:20",
    unreadCount: 0,
    isOnline: true,
  },
  {
    id: 6,
    name: "Nigora Ismoilova",
    message: "Tez orada ko‘rishamiz 😉",
    lastMessageTime: "Kecha",
    unreadCount: 3,
    isOnline: false,
  },
  {
    id: 7,
    name: "Shoxrux Qodirov",
    message: "Tayyor bo‘lsangiz qo‘ng‘iroq qiling",
    lastMessageTime: "07:55",
    unreadCount: 0,
    isOnline: true,
  },
  {
    id: 8,
    name: "Zarina Xudoyberdiyeva",
    message: "Zo‘r chiqibdi 🔥",
    lastMessageTime: "12:10",
    unreadCount: 4,
    isOnline: true,
  },
  {
    id: 9,
    name: "Azizbek Yo‘ldoshev",
    message: "Ishlayapman...",
    lastMessageTime: "Kecha",
    unreadCount: 0,
    isOnline: false,
  },
  {
    id: 10,
    name: "Malika Sobirova",
    message: "Katta rahmat 🙌",
    lastMessageTime: "13:33",
    unreadCount: 2,
    isOnline: true,
  },
];

export default mock_users;
